### ISSUE TITLE
Work required to make it work with tss directly?

### ISSUE THREAD

**Issue by faceleg** [mhartington/deoplete-typescript#1]
For some reason Tsuquyomi is amazingly slow and not reliable with my setup.

 - I'm using Neomake for tsc error checking, and YCM for autocomplete.
 - I'd rather use deoplete because compiling C code is annoying.

How much work would be required to make this deoplete source work directly with TSS?

Could you point me in the right direction, in terms of where to start?

**Comment by mhartington** [comment]
This is something I'm currently investigating. My python abilities and familiarity with TSS are a bit of a limitation, but it should go something like this.


- Setup deoplete settings
- Start a server using subprocess and keep it open
- on tigger, send the request to stdin that follows this pattern
https://github.com/Quramy/tsuquyomi/blob/master/autoload/tsuquyomi/tsClient.vim#L136

```
{'command': a:cmd, 'arguments': a:args, 'type': 'request', 'seq': s:request_seq}
```

- build up response from that request by reading stdout

Rough idea pulling pieces from 

https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py

and 

https://github.com/Quramy/tsuquyomi/blob/master/autoload/tsuquyomi/tsClient.vim

If you're interested in helping out, I'd love to get this to use deoplete only too.

**Comment by faceleg** [comment]
A mix of

 - https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py
 - https://github.com/Valloric/ycmd/blob/master/ycmd/completers/typescript/typescript_completer.py

Should do it.

Are there any resources describing the best practise for plugin development when using dein?

**Comment by mhartington** [comment]
I just add 

```
  call dein#local('~/GitHub', {},['deoplete-typescript'])
```

Were the first path is the path to directory that has the plugin folder, and the second name is directory for the plugin.

**Comment by faceleg** [comment]
I've made a hilariously hacky start here: https://github.com/faceleg/deoplete-typescript/tree/feature/tss-neovim

**Comment by faceleg** [comment]
Current status: 

 - Pulled in a TSServer wrapper from some ycmd code.
 - Failed at making it communicate properly with tsserver, should work OK once that is sorted though
 - Failing to grok the tsserver communication protocol defined here: https://github.com/Microsoft/TypeScript/blob/2cb0dfd99dc2896958b75e44303d8a7a32e5dc33/src/server/protocol.d.ts it's not incredibly complex, there just doesn't seem to be a clear explanation of the commands or any examples. Should be able to infer what we need from the ycmd file, unless better documentation comes along.

This is my first try at python, so if you @mhartington or anyone else feels like banging it out, feel free!

**Comment by faceleg** [comment]
Closing, move discussion to PR thread.
