### ISSUE TITLE
Pass arguments to TSC?

### ISSUE THREAD

**Issue by skorlir** [mhartington/deoplete-typescript#10]
Maybe I'm just failing to grok something about makeprg (is makeprg being used behind the scenes here? I don't even know), but it would be killer to be able to use the `-p` flag to tell the completer that `tsconfig.json` is not in the same directory.

**Comment by mhartington** [comment]
Currently, we're not using `tsc` at all here. The typescript package on npm ships with `tsc` and `tsserver`, so that's all that being used.
https://github.com/mhartington/deoplete-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py#L39

**Comment by skorlir** [comment]
Then I'm asking for the ability to set the project directory to something other than `cwd`. Because my tsconfig won't always be in `cwd`, and may not even be in a parent directory, since I can use the `-p` flag to specify my project configuration location with TypeScript since... [1.8, it looks like](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#the---project--p-flag-can-now-take-any-file-path).

**Comment by mhartington** [comment]
Chances are, this may not even need to know about tsconfig, since again it doesn't touch anything with the compiler.

**Comment by skorlir** [comment]
Okay but what about typings? How does the completer know about typings if
it has no knowledge of tsconfig?

I feel like typings are an important use case. It is desirable to be able
to autocomplete from TypeScript lib typings, at least - and these vary with
regard to target and other compiler options. I suppose it may be that
tsserver doesn't support them, but I feel like it must... Or otherwise
should.

**Comment by mhartington** [comment]
Ahh, forgot about typings. In this case, the current setup work for most projects.

But for what you're suggesting, it's a bit of a can of worms. Specifically how the server starts, and the  order of operations for that. Opening nvim from the root project with the tsconfig is really the only clean way to keep a reliable process.

**Comment by skorlir** [comment]
Would it be possible to give the user the ability to configure the project
root themselves? I can imagine a vim autocmd that would work for me, but
I'd have to be able to tell deoplete-typescript what the project directory
is instead of relying on process.cwd().

**Comment by mhartington** [comment]
It isn't that easy with deoplete. Best option honestly, keep your current vim session/pwd in the directory that has the tsconfig for your project.

**Comment by skorlir** [comment]
Ach. Well, thanks anyway!
