### ISSUE TITLE
Feature requests/Implementations

### ISSUE THREAD

**Issue by DonnieWest** [mhartington/deoplete-typescript#11]
Not really sure where to put this or how to broach this so I'm putting it here

I've created a fork [here](https://github.com/DonnieWest/deoplete-typescript) where I just kind of started making changes that were applicable to my needs and I realized some of them might be merged upstream with some care:

Namely, the changes I've made are:

1. Better completion info within the menu
2. Stripped out extraneous information
3. Ability to use this project for Javascript projects using typescript tooling

Other things I would like to do:

1. Make javascript support able to be toggled
2. Update this to work with Typescript 2.0 (not really sure where to begin here, all I know is the plugin crashes when I use 2.0 and my tsserver knowledge is limited)

So, do you want any of this? I don't want to spend the time creating PRs and bugging you if it's not wanted

**Comment by mhartington** [comment]
Hey just looked over the changes in your fork. Yes, please send a PR! 

Some of this I had locally and was testing out some refactoring, but would be happy to have you add it :grin:

**Comment by DonnieWest** [comment]
@mhartington thanks! I've started the process with #13 

I've some more work to do on Javascript project support so that will come later. For now I'll close this :D
