### ISSUE TITLE
Issues with TS 2.0?

### ISSUE THREAD

**Issue by faceleg** [mhartington/deoplete-typescript#15]
Getting this in `:messages` when using with TypeScript@2:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/sources/typescript.py", line 139, in gather_candidates
[deoplete]     if (entry["kind"] != "warning"):
[deoplete] TypeError: string indices must be integers
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/sources/typescript.py", line 139, in gather_candidates
[deoplete]     if (entry["kind"] != "warning"):
[deoplete] TypeError: string indices must be integers
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 73, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/faceleg/.cache/nvim/dein/.dein/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
```

Haven't had a chance to start debugging.

**Comment by mhartington** [comment]
Hmm just about to start my day, but looks like https://github.com/mhartington/deoplete-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py#L139

is causing the issues. @DonnieWest added this.

**Comment by DonnieWest** [comment]
@mhartington I can look into it tonight. It looks like after removing that check, it still fails everywhere else that uses string indices.

**Comment by DonnieWest** [comment]
Reverting back to before my changes still errors out with a similar error here https://github.com/mhartington/deoplete-typescript/blob/dd582eaa74e275c7ec630b4d1b70056cd4ea82e5/rplugin/python3/deoplete/sources/typescript.py#L153

Even fixing some of the errors, it looks like the response from Typescript 2.0 is different enough to foul things up. I can push up some of these fixes, but I think I'd prefer to error out on 2.0 until we have real support for it.

I don't know enough about tsserver to be able to debug this nicely for now. I'd suggest someone else head this up, but if I get some time I might give it a shot

**Comment by faceleg** [comment]
This may be of use: https://github.com/Microsoft/TypeScript/blob/v2.0.0-beta/src/server/protocol.d.ts

**Comment by mhartington** [comment]
I'll poke around and see what up. I personally don't use 2.0 since it's still beta.

Might be worth just grabbing our own copy of the tsserver code and bundling it with the code base for future releases.

**Comment by faceleg** [comment]
I started using 2.0 because @types are much less horrible (no more ///). 

In an ideal world where we all got paid to work on OSS projects, I'd suggest the plugin sniffs for the available TSS version and adjusts it's response handling based on that. 

Bundling the server would make it break for code written for a different compiler, only in new and interesting ways

**Comment by mhartington** [comment]
Hmm, this should be do-able. Hopefully.... we'll just drop support for 1x version of tss once 2.0 is stable and is no longer in beta. 


Will try to look into this tonight!

**Comment by faceleg** [comment]
Yeah, TS seems to move rather fast, and the improvements are often worth the upgrade pain.
