### ISSUE TITLE
Error entering in Typescript files

### ISSUE THREAD

**Issue by Ravencrow** [mhartington/deoplete-typescript#22]
When I enter a typescript file, it pops up this error:
<img width="1616" alt="screen shot 2016-09-24 at 00 32 39" src="https://cloud.githubusercontent.com/assets/3832570/18803342/74b5f978-81ef-11e6-89a8-1c282c0ffa41.png">

I push enter key twice and then I can work, but then I open another typescript file and the same error.

**Comment by mhartington** [comment]
How would I be able to recreate this error? Is there a specific situation? What kind of project? I need more information.

**Comment by mhartington** [comment]
Closing as I am not able to replicate and no steps have been provided to recreate.

**Comment by lukatendai** [comment]
The same error here. Just installed via Plug and gives me the same problem.... Is there any specific configuration of the project? What about nodejs version ?

**Comment by mhartington** [comment]
if you have a tsconfig.json, you should be good to go. Testing a few things out locally, but I have so far not been able to replicate this. Please provide a minimal vim config, as well as a minimal project/use case that I can debug against.

**Comment by lukatendai** [comment]
do you have example project that i can use for testing... also is there any way to get more human readable errors, so there is clear information that tsconfig.json is missing or similar, instead of "Broken pipe". Thank you.

**Comment by mhartington** [comment]
well the tsconfig.json theory is just an idea of what it could be. I'd like to test it more and then prevent the server from even being started if that is the case.
