### ISSUE TITLE
[Bug] deoplete-typescript breaks with TypeScript compiler nightly

### ISSUE THREAD

**Issue by HerringtonDarkholme** [mhartington/deoplete-typescript#25]
Reproduction:

```bash
npm install -g typescript@next
```

With latest nvim, deoplete and deoplete-typescript, expression like `obj.metho` does not have correct completion, but global variable and function.

It works with current stable compiler, more specifically, nightly@20160929 also works.

Really don't what happened here... But I believe it's tsserver's bug.

**Comment by HerringtonDarkholme** [comment]
I suspect this one breaks master https://github.com/Microsoft/TypeScript/pull/11197

**Comment by TiuSh** [comment]
I reproduced the issue with `typescript@2.1.0-dev.20161017`. 
The only thing I could notice is that, given this request:
```
{
    "seq":     16,
    "type":    "request",
    "command": "completions",
    "arguments": {
        "file": "(...)/file.tsx", 
        "prefix": "", 
        "offset": 13, 
        "line": 19
    }
}
```
TSSever@2.0.3 returns:
```
{
    "command": "completions", 
    "request_seq": 16, 
    "seq": 0, 
    "type": "response", 
    "body": [
        {"name": "build", "kind": "function", "sortText": "0", "kindModifiers": "declare"}, 
        (...)
    ], 
    "success": True
}
```
while TSServer@@2.1.0-dev.20161017 now returns:
```
{
    "request_seq": 16, 
    "type": "response", 
    "seq": 0, 
    "message": "No content available.", 
    "command": "completions", 
    "success": False
}
```
But I don't know enough about TSServer to understand if it's a bug or if the request is missing some fields...

**Comment by HerringtonDarkholme** [comment]
Confirmed. tsserver's bug.

Reproduction:

test.ts

```typescript
function a() {}
```

test.tmp

```typescript
function a() {}
a.
```

open tsserver, paste these lines to it.

{ "seq": 1, "type": "request", "command": "open", "arguments": { "file": "test.ts" } }
{ "seq": 2, "type": "request", "command": "reload", "arguments": { "file": "test.ts", "tmpfile": "test.tmp"}}
{ "seq": 3, "type": "request", "command": "completions", "arguments": { "file": "test.ts", "prefix": "", "offset": 3, "line": 2 } }

Expectation:
the response for request 3 will correctly give completions for function.

Actual:
the response3 gave completions for global variables.

**Comment by HerringtonDarkholme** [comment]
Yes, older tsserver uses tempfile.
https://github.com/Microsoft/TypeScript/blob/21c10af13c1297e55a19c49d7dc12cef3d89ecd6/src/server/session.ts#L899

**Comment by HerringtonDarkholme** [comment]
Closed via https://github.com/Microsoft/TypeScript/pull/11694/files

**Comment by mhartington** [comment]
Well then.... 

thanks for looking into this @HerringtonDarkholme ! Really appreciate the extra set of eyes!
