### ISSUE TITLE
Not work on '*.tsx' file

### ISSUE THREAD

**Issue by acomagu** [mhartington/deoplete-typescript#31]
This plugin causes python error on editing files set "filetype=typescript" but the extension is not .ts.

    [deoplete] Traceback (most recent call last):
    [deoplete]   File "/home/yuki/.config/nvim/dein.vim/.cache/init.vim/.dein/rplugin/python3/deoplete/deoplete.py", line 98, in gather_results
    [deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
    [deoplete]   File "/home/yuki/.config/nvim/dein.vim/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/typescript.py", line 75, in gather_candidates
    [deoplete]     prefix=context["complete_str"]
    [deoplete]   File "/home/yuki/.config/nvim/dein.vim/.cache/init.vim/.dein/rplugin/python3/nvim-typescript/client.py", line 217, in completions
    [deoplete]     "completions", args, wait_for_response=True)
    [deoplete]   File "/home/yuki/.config/nvim/dein.vim/.cache/init.vim/.dein/rplugin/python3/nvim-typescript/client.py", line 95, in send_request
    [deoplete]     self.__send_data_to_server(request)
    [deoplete]   File "/home/yuki/.config/nvim/dein.vim/.cache/init.vim/.dein/rplugin/python3/nvim-typescript/client.py", line 58, in __send_data_to_server
    [deoplete]     Client.__server_handle.stdin.write(json.dumps(data))
    [deoplete] AttributeError: 'NoneType' object has no attribute 'stdin'
    [deoplete] Could not get completions from: typescript.  Use :messages for error details.

TS Server doesn't start in such situation.
In my case, it is when edit .tsx file.

Thanks.

**Comment by mhartington** [comment]
I'll take a look, should be a simple fix 

Mike Hartington

**Comment by mhartington** [comment]
Do you have a tsx syntax file?

**Comment by acomagu** [comment]
well, I have only Typescript syntax file and set as below:

    autocmd BufEnter *.tsx set filetype=typescript

**Comment by acomagu** [comment]
Now it works.
Thank you!

**Comment by mhartington** [comment]
Yeah I wasn't watching for `.tsx` file in the startup of things. Tested and should be good now.

**Comment by mixedCase** [comment]
@mhartington This seems to be a problem. At least on my end it seems to break with the typescript.tsx filetype, setting ft manually to typescript solves it but of course, breaks TSX indentation.

**Comment by mhartington** [comment]
are you providing a proper syntax file that sets the filetype to typescript.tsx? By default, the server will start on any .tsx file. If this is still an issue, please open a new issue.

![tsx](https://user-images.githubusercontent.com/2835826/33378187-070d0578-d4e2-11e7-9e23-f930ffdba15a.gif)

**Comment by mixedCase** [comment]
Yes. Using leafgarland/typescript-vim and ianks/vim-tsx. The only way to get completion working in the typescript.tsx filetype is with ALE and manually enabling it. nvim-typescript isn't loading its completion unless I manually set the ft to just typescript, breaking proper syntax highlighting and indentation in the process. This is with nvim-completion-manager by the way.

**Comment by Shougo** [comment]
I think nvim-completion-manager does not support `typescript.tsx`.

https://github.com/mhartington/nvim-typescript/blob/master/autoload/cm/sources/typescript.vim#L4

**Comment by mhartington** [comment]
Should be good now, please pull the latest version of the plugin

**Comment by mixedCase** [comment]
@mhartington Working fine now, thanks!

**Comment by NullVoxPopuli** [comment]
I have this type:
![image](https://user-images.githubusercontent.com/199018/43732017-5fa89588-997e-11e8-9978-2681cab08aa0.png)

and the ts server doesn't seem to be starting. is there anything I can do to make it start?

**Comment by mhartington** [comment]
@NullVoxPopuli  Please open a new issue.
