### ISSUE TITLE
How to configure deoplete to use deoplete-typescript as a source

### ISSUE THREAD

**Issue by pyrho** [mhartington/deoplete-typescript#4]
I can't find the information to achieve this :)
Maybe the README.md could use an update !

Thanks !

**Comment by mhartington** [comment]
https://github.com/mhartington/deoplete-typescript#installation

After that it should just work. You will need to have a tsconfig.json present in your directory.

**Comment by pyrho** [comment]
I did that, `echo has("python3")` returns 1.
`.` doesn't trigger completion and Omnicompletion fails.

How should completion be triggered ?
And what can I do to debug the issue ?

Thanks for the quick reply :)

**Comment by HerringtonDarkholme** [comment]
Please ensure tsc is installed globally. 

If you still have problem. Please file your minimal setup as instructed in deoplete.

**Comment by mhartington** [comment]
Going to close. If this is still an issue, please feel free to open an new issue.
