### ISSUE TITLE
Make deoplete-typescript even more responsive

### ISSUE THREAD

**Issue by HerringtonDarkholme** [mhartington/deoplete-typescript#5]
Deoplete-typescript is quite fast for now. But if it is used in a huge file, like TypeScript compiler's [checker.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts), it becomes quite laggy.

The problem here is [every `gather_candidates` call requires an expensive `self._reload`](https://github.com/mhartington/deoplete-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py#L116). If we can reduce the overhead of reloading, then deopelte-typescript can be much faster!

Currently I can come up with two solutions:

1. utilize tsserver's change: for every textchange, tsserver does not need the reload the entire file, rather it can incrementally parse new text inserted.
However, vim's beloved text manipulation is quite hard to be translated into tsserver's format. For example, a macro call/ a block editing/ an autocomplete will change the buffer at multiple places. So deoplete cannot easily tell tsserver where is modified.

2. throttle reload event: 
It is very easy and understandable. say, tsserver does not reload file unless it has not reloaded 1 second ago. It it will break completion sometimes. But deoplete-typescript can make it up by forcing reload.

![screen shot 2016-06-18 at 15 10 35](https://cloud.githubusercontent.com/assets/2883231/16169587/d8fb6b6e-3566-11e6-9e0d-81bae419fe69.png)

This is my try to the second approach. Mere three lines are added. And it will always reload if user inputs a dot. So method hinting is always correct.

After this change, deoplete-typescript is as fast as vscode. Though it is possible to encouter bad completion, I personally does not find it distracting. If you are interesed in this, please tell me if I could submit a pull request.

**Comment by faceleg** [comment]
I can't speak for @mhartington but my gut feeling is that he'd be very interested in a PR!

Your explanation of the problem, analysis and suggested solutions were a joy to read, thanks for putting so much effort in!

**Comment by mhartington** [comment]
PRs are always welcome 😁!

**Comment by mhartington** [comment]
PR accepted and merged into master!

**Comment by HerringtonDarkholme** [comment]
Thanks!
